import 'package:flutter/material.dart';
const kBackGroundColor=Colors.cyan;
const kFillTextFeildColor=Colors.cyanAccent;
const kProductsCollection='Products';
const kProductName='Name';
const kProductPrice='Price';
const kProductCategory='Category';
const kProductDescription='Description';
const KAppBarColor=Colors.deepPurple;
const KbuttonColor= Colors.white;
const kProductImageUrl='Image URl';
const KUserCollection="user";
const KUserPassword = 'Password';
const KUserName = 'userName';
const KUserEmail = 'userEmail';
const KUserConfirmPassowrd='ConfirmPassword';
const KUserMobile='Mobile Number';
const KUserAddress="Address";
